### ISSUE TITLE
Player Select: Press start to join (High priority)

### ISSUE THREAD

**Issue by bradcooper314** [David-Hanna/CS483New#121]
Encountered a glitch where the player select screen screws up as shown [Player 3 - bottom left].

Currently unknown how to reproduce. Not sure if it's merely a graphical glitch (Medium priority) or if the player cannot join/ready for race (High priority). I'll keep trying to reproduce and post a follow-up if successful.

![join-unreproduce](https://cloud.githubusercontent.com/assets/10724128/22977431/839acd86-f35c-11e6-9c04-cfb94d42262c.gif)

**Comment by bradcooper314** [comment]
Update: This is easily reproduced by pressing left/right on any other player BEFORE they have pressed confirm to join. On debug mode this can cause an assertion fail ("Trying to delete nullptr"), and on release mode it shows the problem above.

Doesn't impact gameplay, as having the other players confirm proceeds to race and having the affected player press confirm joins them as normal. Setting to High Priority for how easy it is to accidentally stumble upon and how confusing it can be.

**Comment by David-Hanna** [comment]
Should be an easy fix I'll get to in a couple hours. I find it very strange because I encountered this bug myself already and thought I fixed it.
