### ISSUE TITLE
Multiplayer tournament races end too early (medium priority)

### ISSUE THREAD

**Issue by MatthewWhite** [David-Hanna/CS483New#141]
Races in tournament mode end when there are two drivers left, rather than the current standard of one racer left.

This is due to the fact that `StateRacing::RacerFinishedRace` uses `m_uiNumRacers` for determining if a race is complete, but `m_uiNumRacers` does not account for AI racers.

Steps to reproduce:
1. Launch game
1. Select tournament mode
1. Select n racers where n >= 2
1. Have n - 2 racers finish race

**Comment by MatthewWhite** [comment]
I believe this will be fixed by #146 
@bradcooper314 can you confirm this?

**Comment by bradcooper314** [comment]
Yeah, #146 fixes this issue. I noticed it when I was working on MySQL but forgot to take note of it
