### ISSUE TITLE
Game crashes after first tournament mode race (high priority)

### ISSUE THREAD

**Issue by MatthewWhite** [David-Hanna/CS483New#142]
Finishing the first race in tournament mode causes the game to crash.

Steps to reproduce:
1. Launch game
1. Select tournament mode
1. Select any number of players
1. Finish race

**Comment by MatthewWhite** [comment]
I believe this will be fixed by #146 

@bradcooper314 can you confirm this?

**Comment by bradcooper314** [comment]
Yeah, #146 fixes this too. The issue was the TournamentState was looking in the passed parameters from StateRaceComplete to see where Player0 finished the race in order to place them on the starting line, but this was missing because that information wasn't forwarded to StateRacingComplete
