### ISSUE TITLE
Text rendering bug (High priority)

### ISSUE THREAD

**Issue by MatthewWhite** [David-Hanna/CS483New#149]
Text rendering is seriously borked (Brad, ya dingus).

![brads_shitty_textboxes](https://cloud.githubusercontent.com/assets/8453279/24083658/ff1099f2-0cb9-11e7-8af1-8d1e12e833e0.PNG)

Steps to reproduce:
1. Play game normally until you see janky text

**Comment by bradcooper314** [comment]
I can't seem to reproduce this effect. I'm running Release mode, develop branch, finishing three separate races with normal text. Is this more consistent for you or what are the exact steps to reproduce?

**Comment by MatthewWhite** [comment]
Also running release on develop, Visual Studio 2015.  Seems to happen randomly, but regularly.  A few example I can give are playing as Cleopapa with Speedster on Noob Zone causing race results screen to be messed up.  After that race, I chose Clockmaker with Showoff on Shift Rift and had no issues that race, but then tried again, same kart/driver and track, and the lap counter was messed.  Exited race to main menu, and the main menu was fucked.

@drmacintosh has also had these issues.
