### ISSUE TITLE
Ramp Jump Position (High Priority)

### ISSUE THREAD

**Issue by bradcooper314** [David-Hanna/CS483New#165]
Whenever a player jumps over the ramp, their position is calculated based on the track piece beneath them. As demonstrated in the gif, this can cause a change in position if another player is after this track piece but before the ramp.

To repeat:
1. Have a player positioned between the low point and ramp portion of the Up and Over track
2. Have another player jump over the ramp.

![position-mixup](https://cloud.githubusercontent.com/assets/10724128/24573853/aa57a890-1657-11e7-89d2-a746308e29bc.gif)

**Comment by bradcooper314** [comment]
This is actually high priority because it can activate Cleopapa's Make it Rain ability, causing you to slow down and miss the jump

**Comment by MatthewWhite** [comment]
reassigning to @drmacintosh since he's taking it on this sprint.

**Comment by bradcooper314** [comment]
Addressed by #195
