### ISSUE TITLE
Invisible Walls (Low Priority)

### ISSUE THREAD

**Issue by bradcooper314** [David-Hanna/CS483New#174]
With recent changes to the wall/fence height, the graphics no longer match the physics. Normal driving isn't affected, but air collisions from lobbed abilities (clock bomb) and the jump in Up and Over lead to graphically misleading effects.

Clock bomb collision would be the bigger priority of the two examples, as it is not evident that the clock bomb should bounce and this ends up affecting the strategy of the game.

![wall-bounce](https://cloud.githubusercontent.com/assets/10724128/24684339/41302c7e-1973-11e7-8b59-d2bce6a2313a.gif)

![wall-bounce2](https://cloud.githubusercontent.com/assets/10724128/24684466/439b145a-1974-11e7-841d-7e40c6490d2c.gif)

**Comment by ghost** [comment]
By design! ¯\\_(ツ)_/¯
