### ISSUE TITLE
Select Screen Models (Medium Priority)

### ISSUE THREAD

**Issue by bradcooper314** [David-Hanna/CS483New#191]
The models on the select screen for the different players are all angled slightly different. I'm guessing this wasn't a design decision but just a quick fix to get models on the screen.

![positions](https://cloud.githubusercontent.com/assets/10724128/24927201/343b0634-1ecc-11e7-8385-fb20a6b8e686.png)

**Comment by MatthewWhite** [comment]
This is simply due to different racers being in different "frames" of the "animation".  Not really an issue. Closing
