### ISSUE TITLE
Tidy ComponentKartController::Update

### ISSUE THREAD

**Issue by MatthewWhite** [David-Hanna/CS483New#8]
`ComponentKartController::Update()` is already 140 lines, and will likely grow before it's done.  This isn't readable, so we should fix it now while it's still somewhat small.  The most obvious fix is to create separate functions for all of the different types of control it's working with, such as accelerating, turning, hopping, sliding, etc.  This will create multiple small, readable functions instead of one behemoth, and will aid in maintainability down the road.

**Comment by bradcooper314** [comment]
I'm wondering if this leads itself to a State Machine somehow too: Sliding State, Hopping State, Racing State, etc. Especially when we get into the different debuffs that can disable input, this could get out of hand.

**Comment by David-Hanna** [comment]
Agreed. The state machine topic was brought up under these exact conditions in Carel's class.
