### ISSUE TITLE
Up and Over Track: Ramp wall collision (High priority)

### ISSUE THREAD

**Issue by bradcooper314** [David-Hanna/CS483New#97]
Driving into the walls below ramp landing or below the ramp itself on Up and Over sends racer rocketing into the air.

Reproduce by driving into either wall at a high enough speed and low enough frame rate to clip into wall. 
Easiest to reproduce on Debug mode. Any kart/driver selection works. Reproducible on current develop branch.

Gif shows wall below ramp landing, Release mode, ~22 FPS, Develop branch (Jan. 12), Clockmaker + Juggernaut

![wat](https://cloud.githubusercontent.com/assets/10724128/22069706/60634ab0-dd67-11e6-840a-b0f74deca849.gif)

**Comment by bradcooper314** [comment]
Update: New Pull Request from MacIntosh handles collisions at the base (when next track piece height > 1.0f) but does not resolve when the wall is collided halfway up. This produces less of a vertical jump as vertical force is applied over less time, but still looks funky.

Gif below demonstrates this. Bugfix/collision-accuracy branch, debug mode, 11fps at the time. Can reproduce with difficulty by approaching the wall at roughly 80% speed (turning in midair helps to adjust).

![ramp-bumb](https://cloud.githubusercontent.com/assets/10724128/24583861/d0d1d0ac-1726-11e7-8d12-aea3f129962d.gif)

**Comment by ghost** [comment]
Should be fantastic now

**Comment by bradcooper314** [comment]
Has been minimized as an issue so it's no longer relevant for how little often it can be reproduced.
